### ISSUE TITLE
Level5 XF font image RGB channel doesn't combining

### ISSUE THREAD

**Issue by LITTOMA** [FanTranslatorsInternational/Kuriimu2#100]
**Game Name:** You-Kai Watch  
**Console:** 3DS 
**Format extension(s):**  *.xf
**Type:** font

**Bug details:**

[details]
Every time when drew a new layer, it overwrites the previous one.
I exported the img object after [Xf.cs line 235](https://github.com/FanTranslatorsInternational/Kuriimu2/blob/dev/plugins/Level5/plugin_level5/3DS/Fonts/Xf.cs#L235), see below:
![img1](https://github.com/LITTOMA/bugreports/blob/main/kuriimu-plg-lv5xf-0.png)
![img2](https://github.com/LITTOMA/bugreports/blob/main/kuriimu-plg-lv5xf-1.png)
![img3](https://github.com/LITTOMA/bugreports/blob/main/kuriimu-plg-lv5xf-2.png)

**Runtime:** .NET 5

**Comment by onepiecefreak3** [comment]
PR is merged. Thanks for the contribution.
