### ISSUE TITLE
White box around imported sprites - SOR4

### ISSUE THREAD

**Issue by AyanamiRei1** [FanTranslatorsInternational/Kuriimu2#104]
Streets of Rage 4
Nintendo Switch
No extension
Image

I've ran into an issue in game the new sprites do work however they have a white box around them like this but this only happens with the character select screen for some reason.

![2021-05-01_17-18-27](https://user-images.githubusercontent.com/25233407/116788669-d6cb3e80-aaa2-11eb-86f0-9e77b205575a.png)

It seems to due to the Alpha? being different in an original file it's 00 00 00 00

![image](https://user-images.githubusercontent.com/25233407/116789020-aab0bd00-aaa4-11eb-892b-73df78712987.png)

While in an edited file it's 00 FF FF FF but this might be an per image basis since if you reimport the image and then save it's a mix of both the image on the left is the new and right is the original sprite but reimported.

![image](https://user-images.githubusercontent.com/25233407/116789186-8acdc900-aaa5-11eb-8d00-102e169d1df4.png)

Sample Files
https://drive.google.com/drive/folders/1SdbdfUHiMbGZAM34nrQQyCtssOSCoG0f?usp=sharing

**Comment by onepiecefreak3** [comment]
I added a premultiply filter in the newest dev build, just like SOR4Explorer does premultiplication.

**Comment by AyanamiRei1** [comment]
Perfect its working fine now I'll close this now

**Comment by AyanamiRei1** [comment]
Sorry about reopening this but with the SOR4 versions this happens. I was using the batch export and batch import modes.

https://user-images.githubusercontent.com/25233407/116813010-878c1900-ab49-11eb-91b3-fc000d204609.mp4

**Comment by onepiecefreak3** [comment]
Batch operations just use the same plugins as single file operations. Since I do premultiplication as the SOR4 Explorer does, I cannot say how this exactly happens.
However, at this point I'm inclined to blame the image editing software you use. It may change the transparent colors or something. Whatever it is, without samples, I can't do anything.

**Comment by AyanamiRei1** [comment]
Yeah this shouldn't be happening note so far this only happens with edited dxt5 characters.
here's the first frame of SOR4 Blaze
![blaze_0000 00](https://user-images.githubusercontent.com/25233407/116815837-48fd5b00-ab57-11eb-9dc3-44fcaca1d1df.png)
![blaze_0000](https://user-images.githubusercontent.com/25233407/116815853-63cfcf80-ab57-11eb-9491-b8c4f1261e05.png)

and here's some samples
https://drive.google.com/drive/folders/1SdbdfUHiMbGZAM34nrQQyCtssOSCoG0f?usp=sharing

**Comment by onepiecefreak3** [comment]
DXT5 doesn't have the premultiplication, I wonder if that is the cause of this problem.
I will add the premultiplication for each encoding and we see if this helps in any way.

**Comment by onepiecefreak3** [comment]
The newest dev build has those changes now. Update and try again.

**Comment by AyanamiRei1** [comment]
Perfect! Now this issue should stay closed.
![image](https://user-images.githubusercontent.com/25233407/116824443-33515b00-ab82-11eb-8966-8500a23f9d66.png)
