### ISSUE TITLE
CPK Editing causes game to hang

### ISSUE THREAD

**Issue by InochiPM** [FanTranslatorsInternational/Kuriimu2#116]
**Game Name:** Dia no kuni no alice  
**Console:**  PSP
**Format extension(s):**  .CPK
**Type:** Archive 

**Bug details:**
When replacing a file in the DATA0.CPK with Kuriimu2 the file prologue.ks foes from 3333kb to 3336kb with this beingthe olny file edited some how the whole CPK file goes down in file size rather than go up when the ks file is edited. 
This causes the came to forever hang on the "Now Loading" screen when trying to play it. 

However using the CPK tools found online editing the files then repacking the CPK entirely doesn't cause this issue.
 
**Sample files (if possible):**
CPK Vanila
https://www.dropbox.com/s/m8frtg619ydd7i1/DATA0.cpk?dl=0

CPK Edited
https://www.dropbox.com/s/qrcrnesgx3gppql/DATA0_Edit.cpk?dl=0

Edited Prologue.ks
https://www.dropbox.com/s/6lwj3yxaxy57t10/prologue.ks?dl=0

**Comment by onepiecefreak3** [comment]
A bug was fixed in the newest dev build, which sorts the files correctly to correlate with an optionally existing CpkExtendedId table.
