### ISSUE TITLE
TARC files

### ISSUE THREAD

**Issue by InochiPM** [FanTranslatorsInternational/Kuriimu2#124]
**Game Name:**  Tongari Boushi 3DS
**Console:**  3DS
**Format extension(s):**  .tarc
**Type:** archive

**Bug details:**
When opening the files menu_input_magic.tarc & menu_input_magic2.tarc from Tongari boushi they refuse to open throwing an Exception Error for those files as well as a few others.. 
![2021-05-26 16_16_30-Exception catched](https://user-images.githubusercontent.com/13459080/119725426-eb022180-be3d-11eb-82e5-db8f9465bea5.png)
![2021-05-26 16_16_41-Kuriimu2 1 2 0-845233579 - plugin_konami dll - TARC - f7d52572-b076-4f0d-b7c2-53](https://user-images.githubusercontent.com/13459080/119725428-eb022180-be3d-11eb-80cb-716a84a59d5b.png)

**Sample files (if possible):**
https://www.dropbox.com/sh/zzor9o39jpknwyl/AACWwNauCvSKffGa3pzKPZ0ka?dl=0

**Comment by onepiecefreak3** [comment]
This is solved in the newest dev build and upcoming Release 1.2.1.
