### ISSUE TITLE
Tales of Innocence R - L7C repack?

### ISSUE THREAD

**Issue by pnvnd** [FanTranslatorsInternational/Kuriimu2#136]
Awesome tool! I was able to extract the files in `toidata_release.l7c` with the Bandai Namco plugin.  Is there any feature coming or instructions on how to repack these file?  I tried modifying and replacing one of the files, then saved it but it's giving me an error on my Vita.  Am I doing something wrong?  It loads, then crashes like these screenshots:

![image](https://user-images.githubusercontent.com/65086728/122848547-be73e500-d2d7-11eb-98db-abe8d2c7e86d.png)
![image](https://user-images.githubusercontent.com/65086728/122848396-70f77800-d2d7-11eb-910d-d0a385efbb0d.png)

**Comment by IcySon55** [comment]
What is the storage medium of your `ux0:` on your Vita?

**Comment by pnvnd** [comment]
My `ux0:` is an official Sony PSVita 8GB memory card:
![image](https://user-images.githubusercontent.com/65086728/122857741-f9314980-d2e6-11eb-9800-5dc3140d9138.png)

I'm also using a PSTV if that matters.
![image](https://user-images.githubusercontent.com/65086728/122857890-431a2f80-d2e7-11eb-9a41-14da832d8b0b.png)

**Comment by IcySon55** [comment]
That error message looked familiar. I'm not 100% sure about it, but that's probably the error I used to get when using my defective 64GB Vita memory card.

**Comment by pnvnd** [comment]
Thanks!  I'll try again with another memory card and will report back here.

**Comment by FistingUranus** [comment]
![image](https://user-images.githubusercontent.com/77898683/122919289-0faec380-d32e-11eb-981b-62e20faacc7e.png)

**Comment by onepiecefreak3** [comment]
I'm interested in pursuing this issue further. If there is a discord or a user group, where this can be further discussed in detail, without spamming this comment section here, just message me, or send me an invite.
Just to mention it, I'm the main dev of Kuriimu2 and also the author of this plugin, so I'm not just any random guy ^^

**Comment by pnvnd** [comment]
Discord channel: https://discord.gg/tmDgBDNPpE

**Comment by onepiecefreak3** [comment]
The issue is closed.
Problem was missing re-chunking of replaced files into the proper chunk sizes, defined by the L7c header. The code currently assumes a max chunk size of 0x10000 bytes. Recompressing a file into chunks of that max size can take quite a while, so be patient while the application saves the file (especially if it is >1GB)
