### ISSUE TITLE
.psarc Error 

### ISSUE THREAD

**Issue by InochiPM** [FanTranslatorsInternational/Kuriimu2#137]
**Game Name:**  Shiro to Kuro no Alice
**Console:**  PS Vita
**Format extension(s):**  .psarc
**Type:** archive

**Bug details:**
When loading the .psarc it throws an header error.
![image](https://user-images.githubusercontent.com/13459080/123387255-939ec080-d565-11eb-90f3-a345d1f7f8b3.png)

**Sample files (if possible):**
https://www.dropbox.com/s/z9xy42v0eeexsi2/script.psarc?dl=0

**Comment by onepiecefreak3** [comment]
This issue is now resolved in the newest dev build and upcoming Release 1.2.1.
I actually can not tell you where the issue was exactly. After ~30 minutes of refactoring and debugging, the sample started to work and after some more testing, the extracted files were also as expected.
