### ISSUE TITLE
Namco - L7c archive type

### ISSUE THREAD

**Issue by StorMyu** [FanTranslatorsInternational/Kuriimu2#14]
used in some PsVita games, most of its information can be found at:
[https://github.com/solaris573/taikotools/tree/master/psvita-l7ctool/psvita-l7ctool](url)
meanwhile, the smallest L7c I could find, from Tales of Hearts Infinity Evolve: [https://www.mediafire.com/file/50dqqi0ad3dq9q9/tohdata_release.l7c/file](url)

**Comment by onepiecefreak3** [comment]
Implemented in K1 and will therefore be ported over at a later point. The plugin was tested with Tales of Hearts R and Tales of Innocence R, so it is assumed to work.
