### ISSUE TITLE
Monster Hunter Stories 2 .arc files incompatible

### ISSUE THREAD

**Issue by lori9** [FanTranslatorsInternational/Kuriimu2#141]
**Game Name: Monster Hunter Stories 2**  
**Console: Switch**  
**Format extension(s): .arc**  
**Type:** Archive

**Bug details:**

The game appears to be on an enhanced MT framework engine with .arc files storing all content, similar to the first game. When attempting to open .arc files using the new tool, I get "Specified Argument as out of the range of valid values. (Parameter 'length')"

**Sample files:**

https://mega.nz/file/nL4igSbY#trusvc2LCadYDr1k4T9IbqoZie7loIlZHrpbnPvHJ8U

**Comment by onepiecefreak3** [comment]
The newest dev build and upcoming Release 1.2.2 will fix this issue.
The entries had a size of 0x90 bytes, while all other known arc versions only had an entry size of 0x50 bytes. This is identified and fixed.
With that we also checked that the tex contained in the sample work and applied another fix to support MtTex version A3, and added support for the image encoding 0x20 for the Switch platform.

For more erquests and bug reports on those formats, create another issue.
