### ISSUE TITLE
[Bug] 1.2.1 MT Framework bugs when opening or exporting tex files

### ISSUE THREAD

**Issue by MikoMMM** [FanTranslatorsInternational/Kuriimu2#146]
**Game Name: Sengoku Basara 4**  
**Console: PS3\PS4**  
**Format extension(s): tex**  
**Type:** [ image ]

**Bug details:**
When opening or exporting tex files, the program spits out a strange error
![Screenshot_2021-07-07_122246](https://user-images.githubusercontent.com/33367804/124884593-b653bf00-dfd2-11eb-9724-7260ec7bbdcf.png)

And another one with another .arc file
![image](https://user-images.githubusercontent.com/33367804/124900073-033e9200-dfe1-11eb-9352-e9be53c1654f.png)

The errors only seem to happen on version 1.2.1, the tex files open perfectly fine on 1.2.0

**Sample files (if possible):**
Sample with tex files for testing: https://mega.nz/file/wewXlA6a#pkGOeNJvqLLXyuBRGCqPA-3S1Q6uq5YoFK8OkuIt0Q4
and another arc file with the 2nd error: https://mega.nz/file/dS41gSKL#Kzz3mdhbv12vpulyNDsuhTB8SLazO53Pm6A5VfJ9HY4

**Comment by onepiecefreak3** [comment]
Those cannot be reproduced on the newest dev build of Kuriimu2. Therefore this issue will be closed.
