### ISSUE TITLE
[Bug] Certain .texes from certain .arcs don't get overwritten by .pngs

### ISSUE THREAD

**Issue by MikoMMM** [FanTranslatorsInternational/Kuriimu2#147]
**Game Name: Sengoku Basara 4**  
**Console:PS3\PS4**  
**Format extension(s): tex**  
**Type:** image

**Bug details:**
So, when I open a character model arc, which holds model textures and the like, and when I open the textures and try to replace them, this happens after overwriting a tex with a png, the texture and the file stays the same, but the program says the importing is finished.

![image](https://user-images.githubusercontent.com/33367804/124965590-9815af80-e022-11eb-9d04-4af43babae94.png)

**Sample files (if possible):**
Here's the tex which this issue occurs on: https://mega.nz/file/hSIwGBiJ#oPwLzMltZW8F8gmYZA48AoWXmsBAVHaRgyO8IndZtBo

**Comment by onepiecefreak3** [comment]
Bug is solved in the newest dev build. The problem was that PS3 tex actually missed reading the main image data and only read the mip maps.
