### ISSUE TITLE
TMC , TMCL files

### ISSUE THREAD

**Issue by Alblowi12** [FanTranslatorsInternational/Kuriimu2#152]
**Game Name:**   ninja gaiden 3
**Console:**  nintendo switch 
**Format extension(s):**   tmc , tmcl
**Type:** [ text | image | archive | font ] texture

**First 8 or more bytes of the file(s):**
[extension] - [bytes in hex] - [bytes in ASCII]

**More details:**
[details]
tmc files , tmcl files which contains model and texture ,  texture use header GT1G0600 
**Sample files (if possible):**

[links]
[switch.zip](https://github.com/FanTranslatorsInternational/Kuriimu2/files/6797232/switch.zip)

**Comment by IcySon55** [comment]
Please do not attach files to issues. Follow the instructions!
