### ISSUE TITLE
ZLib-SARC archives

### ISSUE THREAD

**Issue by flvinny** [FanTranslatorsInternational/Kuriimu2#162]
**Game Name:**  Rhythm Heaven Megamix
**Console:**  Nintendo 3DS
**Format extension(s):**  .zlib
**Type:** Archive

**First 8 or more bytes of the file(s):**
agbBatter_long.zlib - 00 3A 1E F5 78 9C EC 9D 09 - �:õxœì	
treasure_world_data.zlib - 00 00 1C A5 78 9C B5 58 7D - ��¥xœµX}
coffee_shopItem.zlib - 00 0C 03 28 78 9C EC 5D 09 - �(xœì]	

**More details:**
Supported by Kuriimu1's Karameru (except for the file coffee_shopItem.zlib, which always fails to save)

**Sample files (if possible):**
https://drive.google.com/drive/folders/1Gy5vFT3Fv0dewLhUg2ThgvYiiRF90r9q?usp=sharing

**Comment by onepiecefreak3** [comment]
Support for those is added in the newest dev build and upcoming Release 1.2.2.
Issue closed.
