### ISSUE TITLE
Unsupported .tex format 

### ISSUE THREAD

**Issue by SamuraiOndo** [FanTranslatorsInternational/Kuriimu2#167]
There are some textures in The Great Ace Attorney Chronicles (PC) that are unsupported.  

The only one that I have found is EF01_BM_NOMIP.tex from chr000.arc.

When I try to load it into Kuriimu2, the dev build, I get the error of "The given key "54" was not present in the dictionary."

Example file:
https://mega.nz/file/aLIQXbSB#e2cJ6C4kf9A3i5OE_OROw37DBU0oeuYSExgXix3nygc

**Comment by onepiecefreak3** [comment]
The newest dev build adds the missing encoding 0x36. Isse closed.
