### ISSUE TITLE
.TEX files changing issue

### ISSUE THREAD

**Issue by Mitsu-san** [FanTranslatorsInternational/Kuriimu2#170]
**Game Name:** The Great Ace Attorney Chronicles 
**Console:** PC
**Format extension(s):** .TEX
**Type:** [ image ]

**Bug details:**
When I trying to change .TEX file, in game it becomes black or something.
*Step by step video:* https://drive.google.com/file/d/1WrPRWkTp-IjWK4gj4gk3B5TQE-KVy7Fz/view?usp=sharing
(Sorry for huge video file)

**Sample files:**
*My files:* https://drive.google.com/drive/folders/12Qt_Og4puxUAiapXnbfm_R010IkgmqhG?usp=sharing
*Original files:* https://drive.google.com/drive/folders/1cPLitm7raphbt-4UraAlvk7pxJ8M5mc9?usp=sharing

**Comment by onepiecefreak3** [comment]
The newest dev build fixes this bug by writing the data offset instead of the total data size for PC MtTex.
This confusion happened, since Switch and PC MtTex use mostly the same code, but this value differs between the 2 platforms and was not correctly set for PC MtTex.
