### ISSUE TITLE
[TGAAC] Some arc file save error occurred

### ISSUE THREAD

**Issue by saivenx** [FanTranslatorsInternational/Kuriimu2#172]
**Game Name:**  
The Great Ace Attorney Chronicles

**Console:**  
PC

**Format extension(s):**  
*.arc

**Type:** [ text | image | archive | font ]
archive

**Bug details:**
A typical arc file can be modified normally to the current version.
However, there are files that generate errors when saving.
All I did was replace the gmd file.

I extracted the gmd file as a test and tried to insert it as it was, but the same error occurred.

The version used is Kuriimu2 EtoForms Dev #213
![tests](https://user-images.githubusercontent.com/22842194/129467751-5e0b1e9e-e6e2-4f9e-a25f-04a695c0d3ef.JPG)

**Sample files (if possible):**
[links]
Files that are normally modified.
https://mega.nz/file/2xwiFAIQ#7imhD2vz2jc4yEd5e2-0kUiiSCtiRRGMzlZbIcRkZuc

Error file.
https://mega.nz/file/G05QCaxB#y2BnZ2rMBGoJK02deBx1NVJ7MlPRSUR-7MaYh8QcFTE

**Comment by onepiecefreak3** [comment]
This is now fixed in the newest dev build. Issue closed.
