### ISSUE TITLE
One Piece: Super Grand Battle! X JArc import

### ISSUE THREAD

**Issue by SamuraiOndo** [FanTranslatorsInternational/Kuriimu2#174]
**Game Name:**  
One Piece: Super Grand Battle! X
**Console:**  
3DS
**Format extension(s):**  
.jarc
**Type:** [ text | image | archive | font ]
archive

**Bug details:**
JArc files are completely different when importing the same image

**Sample files (if possible):**
https://mega.nz/file/ldgAmC4K#zPXznoSVIwwibLaeT2ILF0FOOtNdP0ojic4grkby8Mk

**Comment by onepiecefreak3** [comment]
The newest dev build fixes this by properly writing the file offsets now.
