### ISSUE TITLE
 Metroid Samus Returns  - PKG archive Font Tex

### ISSUE THREAD

**Issue by JokerDKha** [FanTranslatorsInternational/Kuriimu2#179]
**Game Name: Metroid Samus Returns **  
**Console:Nintendo 3DS**  
**Format extension(s):pkg. mtxt**  
**Type:** [ | archive | Font Tex ]

**First 8 or more bytes of the file(s):**
Pkg:
7C 00 00 00 07 01 10 00 01 00 00 00 82 52 B1 27 - TEX |�������‚R±'
Mtxt:
4D 54 58 54 01 00 04 00 01 00 05 00 00 04 00 00 - TEX MTXT�������
**More details:**
https://github.com/TeamPBCN/Metroid-Samus-Returns

**Sample files:**
pkg file
https://drive.google.com/file/d/1lj_lNOyDmdiAwBJ4Yz_qyzAURNXTySWI/view?usp=sharing
mtxt file
https://drive.google.com/file/d/1WsEhOcwQIe-x_0bAeabBBbwzV9I7zw7A/view?usp=sharing

**Comment by onepiecefreak3** [comment]
I don't know why this issue was closed, but MTXT is supported in the newest dev build and upcoming Release 1.2.2.
