### ISSUE TITLE
BCMA internal .arc files error

### ISSUE THREAD

**Issue by InochiPM** [FanTranslatorsInternational/Kuriimu2#181]
**Game Name:**  N/A
**Console:**  3DS
**Format extension(s):**  .arc
**Type:** Archive 

**Bug details:**
This file comes from within the .bcma file they have a few bytes before the darc header so it causes K2 to not open them.

**Sample files (if possible):**
![2021-08-24 20_57_40-wxMEdit -  C__Users_InochiPM_Desktop_Manual_Export_JPN_ja_index arc](https://user-images.githubusercontent.com/13459080/130709391-bd5e7217-752d-46ab-9fca-42520e461105.png)
![2021-08-24 20_57_31-wxMEdit -  C__Users_InochiPM_Desktop_Translation   Hacking_Enchanted_folk_Extrac](https://user-images.githubusercontent.com/13459080/130709392-f9ddf4e3-a64a-4c47-b034-1b3db7e55736.png)

https://www.dropbox.com/s/cb82y4vydte287u/JPN_ja_texture.arc?dl=0

**Comment by IcySon55** [comment]
Sounds like the BCMA plugin isn't providing these files with the correct offset to me.

**Comment by onepiecefreak3** [comment]
For completeness: The darc file was compressed by LZ10. Seeing as how the issue got closed, decompressing the darc seemed to have solved the issue at hand. There is a detection code added to the darc plugin the upcoming Release 1.2.2 and newest dev build.
