### ISSUE TITLE
Cannot rename folder is M.T. Framework ARC files

### ISSUE THREAD

**Issue by SamuraiOndo** [FanTranslatorsInternational/Kuriimu2#183]
**Game Name:**  The Great Ace Attorney Chronciles
**Console:**  PC
**Format extension(s):** ARC 
**Type:**
Archive
**Bug details:**
You cannot rename folders in arc files.  When you rename the folder, it shows up that it's changed, but when you hit save, it resets back to the original folder name. 

**Sample files :**
https://mega.nz/file/BcITSIQa#H_wxWkB24wPD7G_h-HfS0Cs9gf4gnz-iYCSlT8rsUl4

**Comment by onepiecefreak3** [comment]
This bug is fixed in the newest dev build and upcoming Release 1.2.2 of Kuriimu2.
