### ISSUE TITLE
add files to ARC0 archives

### ISSUE THREAD

**Issue by AlePlumber** [FanTranslatorsInternational/Kuriimu2#25]
Game Name:  Inazuma Eleven Go Galaxy
Console:  Nintendo 3ds
Format extension(s):  .fa(ARC0)
Type:  archive
First 8 or more bytes of the file(s):  41 52 43 30 48 00 00 00 64 3B 00 00 0C 4A 00 00
[extension] - [bytes in hex] - [bytes in ASCII]

More details:  
In kuriimu 2 the is an option to delete or rename files in a .fa file. But not to add new files, we need this to install our patch like the update of the game.

Sample files (if possible):  
https://drive.google.com/file/d/1jNHO1cq5ewOfqpID1sPFIz8JPI4xNc1a/view?usp=sharing

**Comment by onepiecefreak3** [comment]
Issue was not reproducable.
Issue is closed.
