### ISSUE TITLE
Plugin Request - .fmg support

### ISSUE THREAD

**Issue by AidanRussellCR** [FanTranslatorsInternational/Kuriimu2#254]
In the first Kuriimu .fmg editing was supported, but you couldn’t reopen files after saving them, but then I noticed that it wasn’t supported at all in Kuriimu2. Will this possibly be added soon or in the future?

**Comment by onepiecefreak3** [comment]
Text formats are generally not available yet in Kuriimu2.
Therefore, text formats also aren't available there yet.
There is not ETA for the feature and we cannot make one at the current date.
