### ISSUE TITLE
XR/FA - Level 5 Unable to save the archive

### ISSUE THREAD

**Issue by longxa762** [FanTranslatorsInternational/Kuriimu2#27]
Game Name:  Inazuma Eleven Go Light EUR
Console:  3DS
Format extension(s):  xr,fa
Type: archive

Bug details:  
Unable to save the archive, whenever I click save it either stuck on saving or say saved successfully but nothing is created/modified. When I try to change the save location to another drive it says Path .. is not rooted to a drive.

![118861364_329962544889238_954277518294518655_n](https://user-images.githubusercontent.com/14937488/92476626-9de40e00-f222-11ea-86d9-46c2a8f59603.png)
![22111](https://user-images.githubusercontent.com/14937488/92476667-ab999380-f222-11ea-8327-d2f4740d5f6c.png)
![2113](https://user-images.githubusercontent.com/14937488/92476673-ae948400-f222-11ea-970a-91d667c61406.png)

Sample files (if possible):  
[ie_a.fa](https://mega.nz/file/Qh1D0Dwa#v2OaDtXigX4iLkJq3j9NGxqJRTtnR1n4TPcL0OcZFsU)
[fix.xr](https://mega.nz/file/c0llzLgQ#neCsUq4lAzahkeaOzVvSl9DW75qYwTWm1-K4-NtHriA)
[log from the Path.. crash](https://mega.nz/file/9w0BCJZL#UxCZ-h2qN2P5hS7V3gHb4oNLSKDnEgB-U8lok9FS6FE)

**Comment by onepiecefreak3** [comment]
The exception is solved in the newest update.
As you can see in your first screenshot, the application is already saving the file, and tells you that, should you attempt to save it another time before finishing. If you save a file by using "Save" (or CTRL+S) the file is saved in-place and not at a new destination, which means the original file will be overwritten after the save operation was successful. It will not overwrite it, if the process encountered an error beforehand.
