### ISSUE TITLE
SHADE - SHTX Images

### ISSUE THREAD

**Issue by obluda3** [FanTranslatorsInternational/Kuriimu2#29]
Game Name:  Inazuma Eleven GO Strikers 2013 (also present in other Shade games like the Vita DR games or  Aa Megami-sama)
Console:  Wii
Format extension(s):  no extension
Type: image

First 8 or more bytes of the file(s):  Header :
6 bytes tag (SHTXFF, SHTXFS, SHTXF4)
4 bytes image height and width (2 bytes each)
2 bytes (changes depending on the file)

Sample files (if possible):  
https://drive.google.com/drive/folders/1oI-4hTBr7ShM2KJLwIbgzTGLlI40UK6d?usp=sharing

More details :
They can be converted to png using Scarlet, and a png can be converted to shtxfs using this : https://gist.github.com/xyzz/fbb344f4c2e9bba1ad12215a72db5035
SHTXFS: After the header, there's a 256 color palette and the actual image.
SHTXFF doesn't have a palette table, every pixel uses 4 bytes (it's a raw image)
SHTXF4 has a 16 colors palette

**Comment by IcySon55** [comment]
You closed the issue without a reason...

**Comment by obluda3** [comment]
Oh, it's because I don't need them, i've already got/written tools for that. I wrote everything i know about them in the issue.

**Comment by IcySon55** [comment]
Ah I see, in future, don't close plugin requests that we haven't completed yet. We would like to support as many files as possible and having closed (effectively hidden) issues won't help with that.

I'd rather keep them open until Kuriimu actually supports the format.

Thanks!

**Comment by obluda3** [comment]
I see, I'll open the other ones as well then.

**Comment by onepiecefreak3** [comment]
@obluda3 Now that you actually implemented your own plugin for SHTX, is this plugin still needed?

**Comment by obluda3** [comment]
The plugin isn't needed, I am going to close the issue.
