### ISSUE TITLE
"Photos With" Series BCLIM Files Cannot Save

### ISSUE THREAD

**Issue by ghost** [FanTranslatorsInternational/Kuriimu2#30]
Game Name: Photos With Mario/Animal Crossing/Pikmin
Console: 3DS
Format extension(s): .BCLIM
Type: [ image ]  

Bug details:  
The program can read and extract/import the image inside the BCLIM just fine, but when trying to save an edited version of this file, it gives an error saying "Non-negative number required. (Parameter 'count')"

Sample files (if possible):  
https://drive.google.com/file/d/1zzQb_WySMoVmVHA9JVyyIXJAkrV-suIB/view?usp=sharing Title Screen logo, trying to save corrupts it

**Comment by onepiecefreak3** [comment]
The issue cannot be reproduced with bclims from the TitleLogo.szs of the named games, and since the given samples are not available anymore we had to guess the files to try to reproduce the issue on.
If the issue persists someone can create another issue for this bug.
