### ISSUE TITLE
BLN Archives - Batch Export bug

### ISSUE THREAD

**Issue by ObludaIE** [FanTranslatorsInternational/Kuriimu2#32]
Game Name:  Inazuma Eleven Go Strikers 2013
Console:  Wii
Format extension(s):  .bln
Type: archive

Bug details:  
When using the batch extract feature for this format, the files are extracted twice in two different folders (mcb0 and mcb1), since BLN archives comes in two (mcb0.bln and mcb1.bln).

Sample files (if possible):   /

**Comment by onepiecefreak3** [comment]
This bug was fixed by Commit e3bbc9c5.
