### ISSUE TITLE
Can't run (missing .NET core despite having it)

### ISSUE THREAD

**Issue by cooolgamer** [FanTranslatorsInternational/Kuriimu2#324]
Kuriimu2 is complaining about .NET core not being installed despite having it installed:

![image](https://github.com/FanTranslatorsInternational/Kuriimu2/assets/64099608/82d85e77-6853-4f82-af7c-f351380a866b)
Pressing "Yes" on this dialog box doesn't work, it just closes and nothing happen.

Can someone give me the link to the right one?

**Comment by RealDarkCraft** [comment]
Install .NET Core : https://dotnet.microsoft.com/fr-fr/download

**Comment by onepiecefreak3** [comment]
As clearly stated in the READ.ME:
You need to have the ".Net Desktop Runtime 3.1.6" for x64 installed on your system.
If you are on Mac or Linux, you can just install the ".Net Runtime 3.1.6" for x64.

You neither have the correct version nor the correct runtime installed.

@RealDarkCraft Your comment also doesn't help, as the link points to the general .NET download page which would point to the newest .NET versions, but not the ones we require as stated in the READ.ME

**Comment by cooolgamer** [comment]
My bad, yep, it was on the readme, it's now working...
I remember that when I checked the readme, it was all about building and not this. I was probably on a other page or something, still thanks
