### ISSUE TITLE
How to convert ImageInfo to Bitmap

### ISSUE THREAD

**Issue by zrct0** [FanTranslatorsInternational/Kuriimu2#33]
I want to write a program that depends on kuriimu2. so it can process some files in batch.
But I don't understand how to convert ImageInfo to Bitmap.
Can someone help me?
Thank you!

**Comment by onepiecefreak3** [comment]
Every image plugin returns an IList<IKanvasImage>. An IKanvasImage contains the method GetImage(), which is a Bitmap in memory, as you need.

**Comment by IcySon55** [comment]
It depends on if he's writing the code at a lower stage (plugin code) or making use of existing image plugins I guess.

**Comment by zrct0** [comment]
perfect. Now it's working

**Comment by onepiecefreak3** [comment]
I will close thos issue then.
