### ISSUE TITLE
Jarc & Jtex Support

### ISSUE THREAD

**Issue by Omnija** [FanTranslatorsInternational/Kuriimu2#37]
Game Name:  One Piece - Grand Battle X 
Console:  
Format extension(s):  [ Jarc | Jtex ]
Type: [ archive | image ]  

First 8 or more bytes of the file(s):  
[extension] - [bytes in hex] - [bytes in ASCII]

More details:  

Jarc are extractable with quickbms, then the jtex are editable with jTexTool.jar. Unable to to repack the jtex into the jarc.

Sample files :  
Jarc 
http://www.mediafire.com/file/zf4ubb4elynjqvl/titlemenu_b_01.jarc/file

**Comment by onepiecefreak3** [comment]
Both jTEex and jArc are supported in Release 1.2.0.
jTex received an update for more compatibility in the newest dev build and in Release 1.2.1

**Comment by onepiecefreak3** [comment]
For clarification here, the mentioned release version may not be available yet. That's why I always mention the newest dev build as well.

**Comment by Omnija** [comment]
Unable to read beyond the end of the stream
https://www.mediafire.com/file/kdp4vww0of7asqb/logo.jarc/file

**Comment by onepiecefreak3** [comment]
Refer to #103 from now on.
