### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by ArisuTheLoli** [FanTranslatorsInternational/Kuriimu2#38]
![8](https://user-images.githubusercontent.com/73005444/96336874-cf9e8f00-1082-11eb-9ac8-e3976dc78bcb.png)

Hello I would like to translate a game but every time I try to open a text or an PNG files with Kuriimu or Kukkii, it shows me this error and I would like to have if it was possible to help me! This is the first time I use Github! Thanks in advance to the people who will help me!

Oh yes, The name of the game is : Beyblade Burst God

The game has 11 files as you can see on the second screen and I'm trying to translate some text but I can't find the text I'm looking for but I can't find it and when I try to import something I get the error of the first screen

![Sans titre](https://user-images.githubusercontent.com/73005444/96337808-fca27000-1089-11eb-887a-0e11ce2b5f9c.png)

**Comment by onepiecefreak3** [comment]
Kuriimu2 is based on plugins. It can't open what it doesn't know. The message you get clearly tells you that Kuriimu2 does not know anything about the files in the game.
Seeing as you mention PNG's as a synonym for images in general, you may be good to have an actual programmer, who understands this kind of stuff, on your translation project.
Each game is different, and so may be its files and file content. If you want us to support anything from this game, you need to create a specific issue for a certain type of file and which plugin you want.

Without looking too deep into this:
Your game text may be in "script", while all the images are in "lytTexture" and maybe "gfx". That is all I can tell you at this point. If none of those files are openable by K2, create an issue for them after you research them yourself a bit.

This concludes the issue.
