### ISSUE TITLE
Dream Club Zero Portable

### ISSUE THREAD

**Issue by RadicalR** [FanTranslatorsInternational/Kuriimu2#39]
Game Name:  Dream Club Zero Portable
Console:  Vita
Format extension(s):  GXT
Type: [ image ]  

First 8 or more bytes of the file(s):  
.gxt- 47 58 54 00 03 00 00 10 - GXT

More details:  
Currently crashes Kuriimu2.

Sample files (if possible):  
Uploaded.

**Comment by onepiecefreak3** [comment]
Since this issue basically requests fixing the "crash" (unhandled exception) thrown by the application itself, it will be closed due to commit 54413930 fixing mentioned behaviour.
To request "fixing" the underlying exception that was thrown by the plugin, create a new issue.
