### ISSUE TITLE
FabStyle - G1T files

### ISSUE THREAD

**Issue by RocketRobz** [FanTranslatorsInternational/Kuriimu2#57]
Game Name:  FabStyle
Console:  Nintendo 3DS
Format extension(s):  G1T
Type: image

Bug details:  
Opening the files give the message: `Some palette encodings are not supported.`

Sample files:  
https://drive.google.com/file/d/1Z4cUSR79BJiipDuoEnQnBdzqaoofqDCo/view?usp=sharing

**Comment by onepiecefreak3** [comment]
The error cannot be reproduced. It's possible that the error was fixed already due to other circumstances leading to a similar error and needed fixing.
The files are fully openable with the newest release.
