### ISSUE TITLE
Open a .fa(GFSA) archive

### ISSUE THREAD

**Issue by plulilith** [FanTranslatorsInternational/Kuriimu2#62]
Game Name:  Layton Kyouju to Majin no Fue
Console:  DS
Format extension(s):  .fa
Type:  archive   

First 8 or more bytes of the file(s):  
[extension] - [bytes in hex] - [bytes in ASCII]

More details:  
Currently   using your fantastic program but I checked if I could open my file with the plugins already installed, I couldn't. 
It's a .fa file but instead of ARC0, it's GFSA.

ps: Thanks a lot for you help last time, you did a very great job by programming this tool :)

**Comment by onepiecefreak3** [comment]
This format is added in the newest version of Kuriimu2.
