### ISSUE TITLE
NISA - BTX (Yuusha Shisu)

### ISSUE THREAD

**Issue by RadicalR** [FanTranslatorsInternational/Kuriimu2#7]
Issue: Plugin Request
Console: Vita
Format extension(s): .BTX
Type: Graphic (Texture)
Game Name: Yuusha Shisu
First 8 byte of file(s):
62 74 78 00 00 01 00 00 00  - btx

More details:
Graphical Format used by Yuusha Shisu

I've uploaded a sample in Discord.

**Comment by onepiecefreak3** [comment]
Added save and many new reverse negineered features.
Those added features are avbailable in the newest dev build and in Release 1.2.1
