### ISSUE TITLE
textures and texture_table - SOR4

### ISSUE THREAD

**Issue by AyanamiRei1** [FanTranslatorsInternational/Kuriimu2#72]
Game Name:  Streets of Rage 4
Console:  Nintendo Switch
Format extension:  No extension
Type: Archive?

First 8 or more bytes of the file(s):  
textures: `5D 00 00 00 8B F0 73 0A 66 65 8C 65 60 60 60 D4 F7 CD 4C 2E CA 2F CE 4F 2B D1 8B C8 4B D4 73 2B 4A CC 4D 2D CF 2F CA D6 73 CE CF 2B 49 CD 2B D1 0B 49 AD 28 29 2D 4A 35 72 09 4A 4D 4C 49 2D 62 00 01 46 16 20 01 C3 8C 40 CC 01 C4 FF 81 60 15`

texture_table `0A 62 00 6C 00 61 00 6E 00 6B 00 00 00 00 00 00 00 00 00 53 00 00 00 6E 61 00 6E 00 69 00 6D 00 61 00 74 00 65 00 64 00 73 00 70 00 72 00 69 00 74 00 65 00 73 00 2F 00 73 00 6F 00 72 00 31 00 2F 00 6F 00 62 00 6A 00 65 00 63 00 74 00 73 00`

More details:  
The texture_table appears to contain the names and locations for the files inside the textures file. I did try using SOR4 Explorer but it refuses to open the files.

Sample files:
https://drive.google.com/drive/folders/1iaIHv5e9e8gPx6p1VyzGfaqjgk_Ia4w7?usp=sharing

**Comment by onepiecefreak3** [comment]
Looking at the SOR4 Explorer, I'm surprised it doesn't open the files. It may be possible that it uses a slightly different approach in the image data than what is expected.
Looking at its code, when decompressing the image, it is expected to have a "XNBw" magic number. However, the images in the Switch version have a magic number "XNBS".
Refer to [Magic Check](https://github.com/jlcebrian/SOR4Explorer/blob/f10b0a8d789f8fd7863c80eb6b4e6f6182d26d4b/Src/TextureLoader.cs#L93) for this.

**Comment by onepiecefreak3** [comment]
This issue will ve resolved in 2 steps, which make supporting other XNB formats from potential other platforms more easy in future revisions (if there should be demand from someone).
First an archive plugin is created which opens the content of texture_table and tetures as a list of decompressed files.
Second an image plugin that can handle XNB images without needing to worry about the compression layer of the data container.

**Comment by AyanamiRei1** [comment]
Oh that's great news thanks a lot!

**Comment by AyanamiRei1** [comment]
One thing though will this allow me and other people to modify the images and use them in game? Probably a dumb question but I thought I'd ask anyway.

**Comment by IcySon55** [comment]
Using modified files in the game they came from is generally the main goal of our tools. :)

**Comment by onepiecefreak3** [comment]
What @IcySon55 said. Our intent with this tool is to load and save file formats.
Modifying and saving those modifications is the whole purpose of this tool and plugin.
So the answer is yes, it will allow modification of the images.

What it may not allow is adding new images or stuff like this. This however has to be researched. The texture_table does have file names, so just adding new textures may as well be possible (if the rest of the game knows how the file is named and can then use it, not the point)

**Comment by onepiecefreak3** [comment]
Loading and saving the texture archive from SOR4 is possible with the newest dev build and available in Release 1.2.1, when it comes out.
Next up is the plugin to actually open and modify the XNB images.

**Comment by onepiecefreak3** [comment]
The Xnb plugin is now available in the newest dev build or in the future Release 1.2.1.
The Xnb plugin can open images with encodings Argb32, Dxt1, Dxt3, and Dxt5. This is even more support than SOR4Explorer. It can save said images as well.
this closes this issue.

**Comment by AyanamiRei1** [comment]
Sorry about reopening this but I have downloaded the newest dev build but I am unable to open up the files due to the plugins being missing from the newest dev builds files.
![image](https://user-images.githubusercontent.com/25233407/116786366-1d666c00-aa96-11eb-914b-6bc550b54952.png)

**Comment by onepiecefreak3** [comment]
Ah, you're right. I forgot to add it to the build list. Thx for reminding.

**Comment by onepiecefreak3** [comment]
It's now added in the newest dev build.
