### ISSUE TITLE
PCK - Level 5 Archive File

### ISSUE THREAD

**Issue by zrct0** [FanTranslatorsInternational/Kuriimu2#74]
**Game Name:** Inazuma Eleven GO 2: Chrono Stone 
**Console:**  3DS
**Format extension(s):**  pck
Type: archive 

**First 8 or more bytes of the file(s):**  
[extension] - [bytes in hex] - [bytes in ASCII]
C1 09 F2 00 00 58 50 43
4B 16 50 05 00 00 47 00

**More details:**  
This file is the only .pck format file in the entire game (gds_pack.pck). It is confirmed that the game character text (like character’s nickname)  is included. We also found some problems about the 3D character model since once we manipulated the file the character models were entirely broken.

**Sample files (if possible):**  

[links]
https://drive.google.com/file/d/1TrKKtlfydu42htpXDdqkmMC_2iyaNFhm/view?usp=sharing

**Comment by onepiecefreak3** [comment]
Idk why you closed it already, but for reference sake:
The gds_pack.pck of Level5 games is the only PCK, that is pre-compressed with LZ11. Decompressing it with LZ11, will make it openable by the Level5 plugin in Kuriimu2.

Also, this plugin is used already in many Inazuma Eleven projects. If there is something broken after your edits, it's not the PCK, but its content you edited.

**Comment by zrct0** [comment]
Thank you for your reply, I really appreciate it.
i closed it because I found the solution right after I posted the question

**Comment by BrunoVieiraL** [comment]
> Thank you for your reply, I really appreciate it. i closed it because I found the solution right after I posted the question

Can you share the solution ?
