### ISSUE TITLE
.lt image support (level 5)

### ISSUE THREAD

**Issue by mrjvs** [FanTranslatorsInternational/Kuriimu2#78]
**Game Name:**  Professor layton - spectres call
**Console:** dsi
**Format extension(s):**  `.lt`
Type: image

**First 8 or more bytes of the file(s):**
.lt
`47 54 58 54 05 00 04 04`
`GTXT....`

**More details:**  
im guessing its an image, its found in an archive that was in a folder named img.
In the archive another smaller file is always present:
.lp - `47 50 4C 54 20 00 08 00` - `GPLT ...`

**Sample files (if possible):**  
https://cdn.discordapp.com/attachments/784481361699274782/827298763440652328/more_files.zip

**Comment by onepiecefreak3** [comment]
The issue is solved in the newest dev build.
GTXT will be available in release 1.2.1.
