### ISSUE TITLE
XI - Scrambled images

### ISSUE THREAD

**Issue by HoldYourWaffle** [FanTranslatorsInternational/Kuriimu2#79]
**Game Name:**  Inazuma Eleven GO Galaxy
**Console:**  3DS
**Format extension(s):**  xi
**Type:** image

**Bug details:**  
The image preview and export of most XI files in `ie6_b.fa/data/img/skill_name` of the aforementioned game seems to be horribly scrambled.

**Sample files (if possible):**
https://drive.google.com/drive/folders/1d27CTrQkdGENnHwnqcCAFDXj7aASoc6_?usp=sharing
This folder contains one of the XI files, a scrambled export from Kuriimu2 and a correct export from Kukkii1.

**Comment by onepiecefreak3** [comment]
The issue was with one of the newest additions to Kanvas.
It introduced a bug, where sizes, that are not a multiple of the swizzle block size, produce the wrong size information for the underlying framework. This will be solved in release 1.2.1 and is implemented in the newest dev build.
