### ISSUE TITLE
NSTP Image Support

### ISSUE THREAD

**Issue by Deathmaw** [FanTranslatorsInternational/Kuriimu2#91]
**Game Name:**  Taiko no Tatsujin: Rhythmic Adventure
**Console:**  Nintendo Switch
**Format extension(s):**  .txp
**Type:** Image

**First 8 or more bytes of the file(s):**
txp (compressed) - 19 80 00 04 07 4E 53 54 50 00 - .....NSTP.
txp (decompressed) - 4E 53 54 50 00 00 01 00 01 00 - NSTP......

**More details:**
Game seems to store images in an "NSTP" container, the Taiko games on VITA did the same but as a VXTP, the txp files appear to be compressed with L7C (same as on VITA) and using a tool to decompress (https://github.com/mariodon/taikotools) and looking at the files in a HEX editor the decompressed Switch compared to decompressed VITA seem pretty similar to VTXP, so I'd imagine the image format is even pretty similar (tga?) but structure just different enough that the existing TXP tool for VITA won't work on them.

Have attached a zip with some sample files with both compressed and decompressed versions of some txp files from Switch, not so worried about Kuriimu including the ability to compress/decompress atm, more want to crack open the images, maybe I should have changed the decompressed to .nstp instead of leaving as .txp...

**Sample files (if possible):**
https://mega.nz/file/J55RwCwb#zeB8Y-qjJJ22Ksv-46mYrM403ogjuGpZJBbFYdoYWTs

**Comment by onepiecefreak3** [comment]
I would like samples for the VTXP format as well.

**Comment by Deathmaw** [comment]
Sure thing.

https://mega.nz/file/hxQnlYBJ#-8hyHpERZo1dMbc0MobDi2U2frXu0pTTlaRHDr5YwL0

**Comment by onepiecefreak3** [comment]
Full support for NSTP was added. It will also apply compression if necessary.
The plugin is available in the newest dev build and will be available in release 1.2.1.

**Comment by Deathmaw** [comment]
Nice! Seems to be working a treat, though I did come across one file that is saying "Given data is too short".

Here is the file.
https://mega.nz/file/FkgEUI5A#8PUJb12HyW4RmT2xqCZVqZpT20zdXSxI6lfVVThBlJg

**Comment by IcySon55** [comment]
Woo more test data! The more the merrier really. Helps us fill out the format spec more completely.

**Comment by onepiecefreak3** [comment]
There is a byte which defines the swizzle to use.
Value 0 is linear swizzle
Value 1 is switch swizzle with automatic expansion.
Thi is changed in the newest dev build and will be included in Release 1.2.1
