### ISSUE TITLE
Cant open Etrian Odyssey Untold HPI/HPB

### ISSUE THREAD

**Issue by Shiriow** [FanTranslatorsInternational/Kuriimu2#95]
**Game Name:**  Etrian Odyssey Untold: The Millennium Girl
**Console:**  3DS
**Format extension(s):**  HPI/HPB
**Type:** archive 

**Bug details:**

Cant be opened with Kuriimu2, just gives a "Specified argument was out of the range of valid values. (Parameter 'length')" error
EO2U, EO5 and EOX work just fine

**Comment by onepiecefreak3** [comment]
This was a bug related to entries found only in Untold 1, which had a size of 0 and an invalid file offset.
When porting the plugin to K2, this minor detail was overlooked and caused the error.
This is fixed in the newest dev build and will be included in Release 1.2.1
